# Generated by Django 2.0 on 2019-04-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0019_remove_userdata_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='lockerno',
            new_name='rollno',
        ),
        migrations.AddField(
            model_name='userdata',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='yod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
