# Generated by Django 2.0 on 2019-04-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0021_auto_20190416_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('yod', models.IntegerField(default=0)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('student1', models.PositiveSmallIntegerField(default=0)),
                ('student2', models.PositiveSmallIntegerField(default=0)),
                ('student3', models.PositiveSmallIntegerField(default=0)),
                ('student4', models.PositiveSmallIntegerField(default=0)),
                ('student5', models.PositiveSmallIntegerField(default=0)),
                ('student6', models.PositiveSmallIntegerField(default=0)),
                ('student7', models.PositiveSmallIntegerField(default=0)),
                ('student8', models.PositiveSmallIntegerField(default=0)),
                ('student9', models.PositiveSmallIntegerField(default=0)),
                ('student10', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
