# Generated by Django 2.0 on 2019-04-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0022_attendancedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedb',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
