# Generated by Django 2.0 on 2019-04-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0023_auto_20190416_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedb',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
