# Generated by Django 2.0 on 2019-04-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0024_auto_20190419_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedb',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
