# Generated by Django 2.0 on 2019-04-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0025_auto_20190422_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedb',
            name='date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
