# Generated by Django 2.0 on 2019-04-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0027_auto_20190422_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='encoding',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
