# Generated by Django 2.0 on 2019-04-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0028_userdata_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='encoding',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='foldername',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
