# Generated by Django 2.0 on 2019-04-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0029_auto_20190425_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='foldername',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
