# Generated by Django 2.0 on 2019-04-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0030_auto_20190427_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='foldername',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
