# Generated by Django 2.0 on 2019-04-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0031_auto_20190427_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancedb',
            old_name='student1',
            new_name='s1',
        ),
        migrations.RenameField(
            model_name='attendancedb',
            old_name='student10',
            new_name='s10',
        ),
        migrations.RenameField(
            model_name='attendancedb',
            old_name='student2',
            new_name='s2',
        ),
        migrations.RenameField(
            model_name='attendancedb',
            old_name='student3',
            new_name='s3',
        ),
        migrations.RenameField(
            model_name='attendancedb',
            old_name='student4',
            new_name='s4',
        ),
        migrations.RenameField(
            model_name='attendancedb',
            old_name='student5',
            new_name='s5',
        ),
        migrations.RenameField(
            model_name='attendancedb',
            old_name='student6',
            new_name='s6',
        ),
        migrations.RenameField(
            model_name='attendancedb',
            old_name='student7',
            new_name='s7',
        ),
        migrations.RenameField(
            model_name='attendancedb',
            old_name='student8',
            new_name='s8',
        ),
        migrations.RenameField(
            model_name='attendancedb',
            old_name='student9',
            new_name='s9',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='rollno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
